# Generated by Django 6.0.3 on 2026-03-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('korneplod', 'Корнеплод'), ('klubneplod', 'Клубнеплоды'), ('kapystnye', 'Капустные'), ('paslenovy', 'Паслёновые'), ('lukony', 'Луковые'), ('tykvenny', 'Тыквенные'), ('zelensky', 'Зелень')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
